version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflared/cert.pem:/etc/cloudflared/cert.pem:ro
    depends_on:
      - frontend
      - backend
