services:
  postgres:
    image: postgres:16-alpine
    container_name: golb_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: golb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d golb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - golb_network

volumes:
  postgres_data:
